import Head from "next/head";
import Image from "next/image";
import Grid from "../components/Grid";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import { SliderData } from "../utils/sliderData";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Next App!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Hero heading="Artsy Lens" message="Collect Moments and Make Memories" />
      <Slider sliderData={SliderData} />
      <Grid />
    </div>
  );
}
